apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokemon-api-client
  namespace: poke-api
  labels:
    app: pokemon-api-client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pokemon-api-client
  template:
    metadata:
      labels:
        app: pokemon-api-client
    spec:
      containers:
        - name: pokemon-api-client
          image: rasec777/pokemon-api-client:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /pokemon/pikachu
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /pokemon/pikachu
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: pokemon-api-client-svc
  namespace: poke-api
spec:
  selector:
    app: pokemon-api-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
